#!/usr/bin/env bash
source "$(dirname "$0")/common.sh"
umask 077
mkdir -p "$FORUM_ROOT/backups"
file="$FORUM_ROOT/backups/forum-$(date -u +%Y%m%dT%H%M%SZ).dump"
# Write to a temporary file: failed backups never look complete.
podman exec "$POSTGRES_CONTAINER" pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc > "$file.tmp"
mv "$file.tmp" "$file"
# Retain the seven latest successful copies. These names are generated by this script.
python3 - "$FORUM_ROOT/backups" <<'PY'
from pathlib import Path
import sys
for p in sorted(Path(sys.argv[1]).glob('forum-*.dump'), reverse=True)[7:]:
    p.unlink()
PY
echo "Резервная копия: $file"
